### ISSUE TITLE
If possible, add a link to AUR.

### ISSUE THREAD

**Issue by nikp123** [RekkyRek/devRantronWeb#1]
AUR is a community packaging system for ArchLinux users.
I just made devRantron availble there.
If possible, add a link: <a href="https://aur.archlinux.org/packages/devrantron/">Availble in AUR</a>

Thanks in advance :)

**Comment by hex2f** [comment]
Oh sorry @nikp123 , I didn't see this before. Definitely adding it :)

**Comment by nikp123** [comment]
ok then xD
